# GitHub Sponsors configuration
# These are supported funding model platforms

# GitHub Sponsors (if you set it up later)
# github: [NexusOne23]

# Buy Me A Coffee
# Support the development of NoID Privacy
buy_me_a_coffee: noidprivacy

# Other platforms (uncomment and add if needed):
# patreon: yourusername
# open_collective: yourusername
# ko_fi: yourusername
# custom: ['https://yourwebsite.com/donate']
