<#
.SYNOPSIS
    Apply audit policies from parsed Security Baseline JSON

.DESCRIPTION
    Uses native auditpol.exe to configure Advanced Audit Policies.
    Applies settings from AuditPolicies.json generated by Parse-SecurityBaseline.

.PARAMETER AuditPoliciesPath
    Path to AuditPolicies.json

.PARAMETER DryRun
    Preview changes without applying

.OUTPUTS
    PSCustomObject with applied count and errors

.NOTES
    Requires Administrator privileges
    Uses auditpol.exe (built into Windows since Vista)
#>

function Set-AuditPolicies {
    [CmdletBinding(SupportsShouldProcess = $true, ConfirmImpact = 'Medium')]
    param(
        [Parameter(Mandatory = $true)]
        [string]$AuditPoliciesPath,

        [Parameter(Mandatory = $false)]
        [switch]$DryRun
    )

    if (-not $PSCmdlet.ShouldProcess($env:COMPUTERNAME, 'Set AuditPolicies')) {
        return
    }


    $result = [PSCustomObject]@{
        Success = $false
        Applied = 0
        Errors = @()
    }

    if (-not (Test-Path -LiteralPath $AuditPoliciesPath -PathType Leaf)) {
        $result.Errors += "Audit policies file not found: $AuditPoliciesPath"
        return $result
    }

    # GUID-suffixed temp files shared across loop iterations (overwritten each round),
    # cleaned up in the finally block at function tail.
    $guid = [Guid]::NewGuid().ToString()
    $stdoutFile = Join-Path $env:TEMP "auditpol_stdout_$guid.txt"
    $stderrFile = Join-Path $env:TEMP "auditpol_stderr_$guid.txt"

    try {
        $auditPolicies = Get-Content -LiteralPath $AuditPoliciesPath -Raw -Encoding UTF8 -ErrorAction Stop |
            ConvertFrom-Json -ErrorAction Stop

        if ($auditPolicies.Count -eq 0) {
            Write-Log -Level DEBUG -Message "No audit policies to apply" -Module "SecurityBaseline"
            return $result
        }
        $seenSubcategories = [System.Collections.Generic.HashSet[Guid]]::new()
        foreach ($policy in $auditPolicies) {
            $parsedGuid = [Guid]::Empty
            if ([string]::IsNullOrWhiteSpace([string]$policy.Subcategory) -or
                -not [Guid]::TryParse([string]$policy.SubcategoryGUID, [ref]$parsedGuid) -or
                -not $seenSubcategories.Add($parsedGuid) -or
                [int]$policy.SettingValue -notin @(0, 1, 2, 3)) {
                throw "Audit policy configuration contains an invalid or duplicate subcategory: $($policy.SubcategoryGUID)"
            }
        }

        Write-Log -Level DEBUG -Message "Applying $($auditPolicies.Count) audit policies..." -Module "SecurityBaseline"
        Write-Host "    Applying $($auditPolicies.Count) audit policies..." -ForegroundColor Cyan

        $currentPolicy = 0
        foreach ($policy in $auditPolicies) {
            $currentPolicy++
            try {
                # Convert SettingValue to auditpol format
                # SettingValue is numeric: 0=No Auditing, 1=Success, 2=Failure, 3=Success and Failure
                # auditpol format: "enable" or "disable" with /success or /failure flags

                $settingValue = [int]$policy.SettingValue
                if ($settingValue -notin @(0, 1, 2, 3)) {
                    throw "Unsupported audit SettingValue '$settingValue'"
                }

                # Build auditpol command using GUID (language-independent!)
                $auditpolArgs = @("/set")
                $auditpolArgs += "/subcategory:$($policy.SubcategoryGUID)"

                switch ($settingValue) {
                    3 {
                        # Success and Failure
                        $auditpolArgs += "/success:enable"
                        $auditpolArgs += "/failure:enable"
                    }
                    1 {
                        # Success only
                        $auditpolArgs += "/success:enable"
                        $auditpolArgs += "/failure:disable"
                    }
                    2 {
                        # Failure only
                        $auditpolArgs += "/success:disable"
                        $auditpolArgs += "/failure:enable"
                    }
                    0 {
                        # No Auditing
                        $auditpolArgs += "/success:disable"
                        $auditpolArgs += "/failure:disable"
                    }
                }

                if ($DryRun) {
                    Write-Log -Level DEBUG -Message "[DRYRUN] Would run: auditpol.exe $($auditpolArgs -join ' ')" -Module "SecurityBaseline"
                    Write-Host "      [$currentPolicy/$($auditPolicies.Count)] $($policy.Subcategory) [DRYRUN]" -ForegroundColor DarkGray
                    $result.Applied++
                    continue
                }

                # Show progress (every 5th policy or first/last)
                if ($currentPolicy % 5 -eq 0 -or $currentPolicy -eq 1 -or $currentPolicy -eq $auditPolicies.Count) {
                    # Remove "Audit " prefix if present for cleaner output
                    $displayName = $policy.Subcategory -replace '^Audit\s+', ''
                    Write-Host "      [$currentPolicy/$($auditPolicies.Count)] $displayName..." -ForegroundColor Gray -NoNewline
                }

                # Execute auditpol; temp files are scoped at function-level (function-unique
                # GUID -- parallel invocations get isolated files) and overwritten each iteration.
                $process = Start-Process -FilePath "auditpol.exe" `
                                         -ArgumentList $auditpolArgs `
                                         -Wait `
                                         -NoNewWindow `
                                         -PassThru `
                                         -RedirectStandardOutput $stdoutFile `
                                         -RedirectStandardError $stderrFile

                if ($process.ExitCode -eq 0) {
                    $result.Applied++
                    # Show success for displayed policies
                    if ($currentPolicy % 5 -eq 0 -or $currentPolicy -eq 1 -or $currentPolicy -eq $auditPolicies.Count) {
                        Write-Host " OK" -ForegroundColor Green
                    }
                }
                else {
                    $stderr = Get-Content $stderrFile -Raw -ErrorAction SilentlyContinue
                    $result.Errors += "auditpol failed for $($policy.Subcategory): $stderr"
                    Write-Log -Level DEBUG -Message "auditpol failed for $($policy.Subcategory): $stderr" -Module "SecurityBaseline"
                    # Show failure
                    if ($currentPolicy % 5 -eq 0 -or $currentPolicy -eq 1 -or $currentPolicy -eq $auditPolicies.Count) {
                        Write-Host " FAILED" -ForegroundColor Red
                    }
                }
            }
            catch {
                $result.Errors += "Failed to set audit policy $($policy.Subcategory): $($_.Exception.Message)"
                Write-Log -Level DEBUG -Message "Failed to set audit policy $($policy.Subcategory): $_" -Module "SecurityBaseline"
            }
        }

        if (-not $DryRun) {
            if (-not (Get-Command 'Get-AuditPolicyState' -ErrorAction SilentlyContinue)) {
                throw 'Get-AuditPolicyState is unavailable for post-apply verification'
            }
            foreach ($policy in $auditPolicies) {
                try {
                    $expected = [uint32][int]$policy.SettingValue
                    $actualFlags = Get-AuditPolicyState -SubcategoryGuid ([Guid][string]$policy.SubcategoryGUID)
                    # SUCCESS and FAILURE are bits 0 and 1. NONE is bit 2;
                    # normalizing to the first two bits maps NONE to SettingValue 0.
                    $actual = [uint32]($actualFlags -band 0x3)
                    if ($actual -ne $expected) {
                        throw "expected SettingValue $expected, got flags 0x$($actualFlags.ToString('X8'))"
                    }
                }
                catch {
                    $result.Errors += "Audit verification failed for $($policy.SubcategoryGUID): $($_.Exception.Message)"
                }
            }
        }

        $result.Success = ($result.Errors.Count -eq 0 -and $result.Applied -eq $auditPolicies.Count)
        Write-Log -Level DEBUG -Message "Applied $($result.Applied)/$($auditPolicies.Count) audit policies" -Module "SecurityBaseline"
        Write-Host "    Completed: $($result.Applied)/$($auditPolicies.Count) audit policies applied" -ForegroundColor $(if ($result.Success) { 'Green' } else { 'Red' })
    }
    catch {
        $result.Errors += "Audit policy application failed: $($_.Exception.Message)"
        Write-Log -Level DEBUG -Message "Audit policy application failed: $_" -Module "SecurityBaseline"
    }
    finally {
        # Clean up the last iteration's temp files (per-loop files are also cleaned each round
        # via the next assignment, but the last pair would otherwise leak).
        if ($stdoutFile -and (Test-Path -LiteralPath $stdoutFile)) { Remove-Item -LiteralPath $stdoutFile -Force -ErrorAction SilentlyContinue }
        if ($stderrFile -and (Test-Path -LiteralPath $stderrFile)) { Remove-Item -LiteralPath $stderrFile -Force -ErrorAction SilentlyContinue }
    }

    return $result
}
